package com.table.navigation

object ArgumentsKeys {
    const val CLASS_ARGUMENT_KEY="CLASS_ARGUMENT_KEY"
    const val STUDENT_ARGUMENT_KEY="STUDENT_ARGUMENT_KEY"
    const val STUDENT_ID_STATISTICS_SCREEN_ARGUMENT_KEY="STUDENT_ID_STATISTICS_SCREEN_ARGUMENT_KEY"
    const val PERIOD_ARGUMENT_KEY="PERIOD_ARGUMENT_KEY"
    const val CLASS_STUDENTS_ARGUMENT_KEY="STUDENTS_LIST_ARGUMENT_KEY"
    const val STUDENT_CALENDAR_ARGUMENT_KEY="STUDENT_CALENDAR_ARGUMENT_KEY"
    const val ADD_SCREEN_CLASS_KEY="ADD_SCREEN_CLASS_KEY"
    const val CLASS_STUDENTS_TEACHER_ID_ARGUMENT_KEY="CLASS_STUDENTS_TEACHER_ID_ARGUMENT_KEY"
    const val ADD_SCREEN_SCHOOL_ID_KEY="ADD_SCREEN_SCHOOL_ID_KEY"
    const val WAITING_SCREEN_CLASS_ID_KEY="WAITING_SCREEN_CLASS_ID_KEY"
    const val WAITING_SCREEN_TEACHER_ID_KEY="WAITING_SCREEN_TEACHER_ID_KEY"
    const val ADD_SCREEN_SCHOOL_NAME_KEY="ADD_SCREEN_SCHOOL_NAME_KEY"
    const val STUDENT_ID_CALENDAR_ARGUMENT_KEY="STUDENT_ID_CALENDAR_ARGUMENT_KEY"
}